# Enable Powerlevel10k Prompt 
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# Specify directory for Antigen bundles
ADOTDIR=$HOME/.zsh/antigen-bundles

# Include Antigen Script
source $HOME/.zsh/antigen/antigen.zsh

# Load the oh-my-zsh's library.
antigen use oh-my-zsh

# Import local plugins
source $HOME/.zsh/plugins/colored-man-pages.zsh
source $HOME/.zsh/plugins/colorize.zsh
source $HOME/.zsh/plugins/interactive-cd.zsh
#source $HOME/.zsh/plugins/docker-auto-complete.zsh # Requires Docker

# Enable autocomplete
autoload -Uz compinit
compinit

# Import local aliases
source $HOME/.zsh/aliases/ansible-aliases.zsh
source $HOME/.zsh/aliases/common-aliases.zsh
#source $HOME/.zsh/aliases/git-aliases.zsh
source $HOME/.zsh/aliases/lol-aliases.zsh
source $HOME/.zsh/aliases/npm-aliases.zsh
source $HOME/.zsh/aliases/tmux-aliases.zsh

# Add plugins to bundle
antigen bundles <<EOBUNDLES
    command-not-found
    zsh-users/zsh-autosuggestions
    zsh-users/zsh-syntax-highlighting
    psprint/zsh-navigation-tools
    StackExchange/blackbox
EOBUNDLES

# Load the theme.
antigen theme romkatv/powerlevel10k

# I'm done- let's go
antigen apply

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
