name: CI
on:
  push:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          mkdir -p ~/dotfiles-install-dir
      - run: |
          HOME=~/dotfiles-install-dir ./install.sh
